const STORAGE_KEY = "focusTodoTasksV1";
const taskForm = document.getElementById("taskForm"), taskInput = document.getElementById("taskInput"), minutesInput = document.getElementById("minutesInput"), taskList = document.getElementById("taskList"), taskTemplate = document.getElementById("taskTemplate"), emptyState = document.getElementById("emptyState"), taskCounter = document.getElementById("taskCounter"), clearCompletedBtn = document.getElementById("clearCompletedBtn"), filterButtons = document.querySelectorAll(".filter-button");
const editModal = document.getElementById("editModal"), editForm = document.getElementById("editForm"), editTaskInput = document.getElementById("editTaskInput"), editMinutesInput = document.getElementById("editMinutesInput"), cancelEditBtn = document.getElementById("cancelEditBtn");
let tasks = loadTasks(), currentFilter = "all", editingTaskId = null, tickerId = null;

function loadTasks(){try{const stored=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(stored)?stored.map(normalizeTask):[]}catch{return []}}
function normalizeTask(task){const durationSeconds=Number(task.durationSeconds)>0?Number(task.durationSeconds):1500;let remainingSeconds=Number.isFinite(Number(task.remainingSeconds))?Math.max(0,Number(task.remainingSeconds)):durationSeconds;if(task.isRunning&&task.startedAt){const elapsed=Math.floor((Date.now()-Number(task.startedAt))/1000);remainingSeconds=Math.max(0,remainingSeconds-Math.max(0,elapsed))}return{id:String(task.id||crypto.randomUUID()),title:String(task.title||"Untitled task"),completed:Boolean(task.completed),durationSeconds,remainingSeconds,isRunning:Boolean(task.isRunning)&&remainingSeconds>0&&!task.completed,startedAt:Boolean(task.isRunning)&&remainingSeconds>0&&!task.completed?Date.now():null}}
function saveTasks(){localStorage.setItem(STORAGE_KEY,JSON.stringify(tasks))}
function createTask(title,minutes){const durationSeconds=Math.round(minutes*60);return{id:crypto.randomUUID(),title,completed:false,durationSeconds,remainingSeconds:durationSeconds,isRunning:false,startedAt:null}}
function formatTime(totalSeconds){const safe=Math.max(0,Math.floor(totalSeconds)),hours=Math.floor(safe/3600),minutes=Math.floor((safe%3600)/60),seconds=safe%60;if(hours>0)return `${String(hours).padStart(2,"0")}:${String(minutes).padStart(2,"0")}:${String(seconds).padStart(2,"0")}`;return `${String(minutes).padStart(2,"0")}:${String(seconds).padStart(2,"0")}`}
function getVisibleTasks(){if(currentFilter==="active")return tasks.filter(t=>!t.completed);if(currentFilter==="completed")return tasks.filter(t=>t.completed);return tasks}
function renderTasks(){taskList.innerHTML="";const visible=getVisibleTasks();visible.forEach(task=>{const node=taskTemplate.content.cloneNode(true),item=node.querySelector(".task-item"),checkbox=node.querySelector(".complete-checkbox"),title=node.querySelector(".task-title"),timerText=node.querySelector(".timer-text"),status=node.querySelector(".timer-status"),start=node.querySelector(".start-button"),pause=node.querySelector(".pause-button"),reset=node.querySelector(".reset-button"),edit=node.querySelector(".edit-button"),del=node.querySelector(".delete-button");item.dataset.id=task.id;item.classList.toggle("completed",task.completed);checkbox.checked=task.completed;title.textContent=task.title;timerText.textContent=formatTime(task.remainingSeconds);const finished=task.remainingSeconds===0;if(finished){status.textContent="Finished";status.classList.add("finished")}else if(task.isRunning){status.textContent="Running";status.classList.add("running")}else status.textContent="Ready";start.disabled=task.completed||task.isRunning||finished;pause.disabled=task.completed||!task.isRunning;reset.disabled=task.completed&&task.remainingSeconds===task.durationSeconds;checkbox.addEventListener("change",()=>toggleTask(task.id));start.addEventListener("click",()=>startTimer(task.id));pause.addEventListener("click",()=>pauseTimer(task.id));reset.addEventListener("click",()=>resetTimer(task.id));edit.addEventListener("click",()=>openEditModal(task.id));del.addEventListener("click",()=>deleteTask(task.id));taskList.appendChild(node)});emptyState.classList.toggle("hidden",visible.length>0);const count=tasks.filter(t=>!t.completed).length;taskCounter.textContent=`${count} ${count===1?"task":"tasks"} left`;clearCompletedBtn.disabled=!tasks.some(t=>t.completed)}
function updateRunningTimers(){const now=Date.now();let changed=false;tasks.forEach(task=>{if(!task.isRunning||!task.startedAt)return;const elapsed=Math.floor((now-task.startedAt)/1000);if(elapsed<=0)return;task.remainingSeconds=Math.max(0,task.remainingSeconds-elapsed);task.startedAt=now;changed=true;if(task.remainingSeconds===0){task.isRunning=false;task.startedAt=null;notifyTimerFinished(task.title)}});if(changed){saveTasks();renderTasks()}}
function startTicker(){if(tickerId)clearInterval(tickerId);tickerId=setInterval(updateRunningTimers,1000)}
function notifyTimerFinished(title){if("Notification" in window&&Notification.permission==="granted")new Notification("Timer finished",{body:title});if("vibrate" in navigator)navigator.vibrate([200,100,200])}
async function requestNotificationPermission(){if(!("Notification" in window))return;if(Notification.permission==="default"){try{await Notification.requestPermission()}catch{}}}
function toggleTask(id){const task=tasks.find(t=>t.id===id);if(!task)return;task.completed=!task.completed;if(task.completed){task.isRunning=false;task.startedAt=null}saveTasks();renderTasks()}
function startTimer(id){const task=tasks.find(t=>t.id===id);if(!task||task.completed||task.isRunning||task.remainingSeconds<=0)return;task.isRunning=true;task.startedAt=Date.now();requestNotificationPermission();saveTasks();renderTasks()}
function pauseTimer(id){updateRunningTimers();const task=tasks.find(t=>t.id===id);if(!task)return;task.isRunning=false;task.startedAt=null;saveTasks();renderTasks()}
function resetTimer(id){const task=tasks.find(t=>t.id===id);if(!task)return;task.isRunning=false;task.startedAt=null;task.remainingSeconds=task.durationSeconds;saveTasks();renderTasks()}
function deleteTask(id){const task=tasks.find(t=>t.id===id);if(!task||!window.confirm(`Delete “${task.title}”?`))return;tasks=tasks.filter(t=>t.id!==id);saveTasks();renderTasks()}
function openEditModal(id){const task=tasks.find(t=>t.id===id);if(!task)return;updateRunningTimers();editingTaskId=id;editTaskInput.value=task.title;editMinutesInput.value=Math.max(1,Math.round(task.durationSeconds/60));editModal.classList.remove("hidden");editTaskInput.focus()}
function closeEditModal(){editingTaskId=null;editModal.classList.add("hidden");editForm.reset()}
taskForm.addEventListener("submit",event=>{event.preventDefault();const title=taskInput.value.trim(),minutes=Number(minutesInput.value);if(!title||!Number.isFinite(minutes)||minutes<1||minutes>1440)return;tasks.unshift(createTask(title,minutes));saveTasks();renderTasks();taskForm.reset();minutesInput.value=25;taskInput.focus()});
editForm.addEventListener("submit",event=>{event.preventDefault();const task=tasks.find(t=>t.id===editingTaskId),title=editTaskInput.value.trim(),minutes=Number(editMinutesInput.value);if(!task||!title||!Number.isFinite(minutes)||minutes<1||minutes>1440)return;const duration=Math.round(minutes*60),changed=duration!==task.durationSeconds;task.title=title;if(changed){task.durationSeconds=duration;task.remainingSeconds=duration;task.isRunning=false;task.startedAt=null}saveTasks();closeEditModal();renderTasks()});
cancelEditBtn.addEventListener("click",closeEditModal);editModal.addEventListener("click",e=>{if(e.target===editModal)closeEditModal()});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!editModal.classList.contains("hidden"))closeEditModal()});
filterButtons.forEach(button=>button.addEventListener("click",()=>{currentFilter=button.dataset.filter;filterButtons.forEach(item=>item.classList.toggle("active",item===button));renderTasks()}));
clearCompletedBtn.addEventListener("click",()=>{if(!tasks.some(t=>t.completed)||!window.confirm("Delete all completed tasks?"))return;tasks=tasks.filter(t=>!t.completed);saveTasks();renderTasks()});
window.addEventListener("beforeunload",updateRunningTimers);renderTasks();startTicker();
